# Generated by Django 3.0.2 on 2020-02-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
