# Generated by Django 3.0.2 on 2020-02-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='branch_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
