# Generated by Django 3.0.2 on 2020-02-11 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_package_branch_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packagestatus',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='packagestatus',
            name='remarks',
            field=models.CharField(default='ongoing', max_length=50),
        ),
    ]
