# Generated by Django 3.0.2 on 2020-02-12 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_auto_20200211_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='cancel',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='package',
            name='branch_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
